# Chapter 3 - Programming Exercises

import math

# 1) Show result of evaluating each expression
#print(4.0 / 10.0 + 3.5 * 2) # 7.4 - float
#print(10 % 4 + 6/2) # 5.0 - float
#print(abs(4 - 20 // 3) ** 3) # 8 - int


#print(math.sqrt(4.5 - 5.0) + 7 * 3) # ValueError: math domain error?? - oh...because it's a negative value

#print(math.sqrt(4.5 + 5.0) + 7 * 3) # 24.082207001484488 -

#print(3 * 10 // 3 + 10 % 3) # 11 - int

#print(3 ** 3) # 27 - int

# Part 2 - translate mathematical expressions into Python expressions
#print((3 + 4) * 5) # 35

#n = 2
#print((n(n - 1)/2)) # TypeError: 'int' object is not callable


# Part 3: Show sequence of #s generated by each of the following range expressions
#for i in range(5):
 #   print('*')

#for i in range(3, 10):
 #   print('*')
#print(range(4, 13, 3))

#for i in range(15, 5, -2):
#    print('*')

#print(range(5, 3))

# 4. Show output generated by following program fragments
# printing 1*1, 2*2, 3*3, 4*4, n*n for range of 11 exclusive (up to 10 rounds)
#for i in range(1, 11):
#    print(i*i)

# 1 : 1
# 3 : 27
# 5 : 125
# 7 : 343
# 9 : 729
# 9
#for i in [1,3,5,7,9]:
#   print(i, ":", i**3)
#print(i)


#x = 2
#y = 10
#for j in range(0, y, x):
#    print(j, end="")
#    print(x + y)
#print("done")

# 012
# 212
# 412
# 612
# 812
# done