# Chapter 3 - Programming Exercises

import math

# 1) Show result of evaluating each expression
#print(4.0 / 10.0 + 3.5 * 2) # 7.4 - float
#print(10 % 4 + 6/2) # 5.0 - float
#print(abs(4 - 20 // 3) ** 3) # 8 - int


#print(math.sqrt(4.5 - 5.0) + 7 * 3) # ValueError: math domain error?? - oh...because it's a negative value

#print(math.sqrt(4.5 + 5.0) + 7 * 3) # 24.082207001484488 -

#print(3 * 10 // 3 + 10 % 3) # 11 - int

#print(3 ** 3) # 27 - int

# Part 2 - translate mathematical expressions into Python expressions
#print((3 + 4) * 5) # 35

#n = 2
#print((n(n - 1)/2)) # TypeError: 'int' object is not callable


# Part 3: Show sequence of #s generated by each of the following range expressions
#for i in range(5):
 #   print('*')

#for i in range(3, 10):
 #   print('*')
#print(range(4, 13, 3))

#for i in range(15, 5, -2):
#    print('*')

#print(range(5, 3))

# 4. Show output generated by following program fragments
# printing 1*1, 2*2, 3*3, 4*4, n*n for range of 11 exclusive (up to 10 rounds)
#for i in range(1, 11):
#    print(i*i)

# 1 : 1
# 3 : 27
# 5 : 125
# 7 : 343
# 9 : 729
# 9
#for i in [1,3,5,7,9]:
#   print(i, ":", i**3)
#print(i)


#x = 2
#y = 10
#for j in range(0, y, x):
#    print(j, end="")
#    print(x + y)
#print("done")

# 012
# 212
# 412
# 612
# 812
# done

# Guess: printing out the number of iterations
# multiplying each iteration and adding them up

#ans = 0
#for i in range(1, 11):
#    ans = ans + i*i
#    print(i)
#print(ans)

# 1
# 2
# 3
# 4
# 5
# 6
# 7
# 8
# 9
# 10
# 385

# What exactly is happening here?
#print(round(314.159265, -1)) # 310.0

# Operands to integer division as negative

# Programming Exercises

# 1. Program to calculate volume and surface area of sphere from its radius, given an input.
# volume = 4/3pi*r ** 3
# I: r (radius)
# O: print volume
# P: v = 4/3pi*r ** 3

def volume():
    import math
    r = eval(input("Enter the radius: "))
    v = 4/3 * math.pi * r ** 3
    print(v)

#volume()


# Calculate surface area
# I: radius
# O: surface area
# P: 4 * pi * r ** 2

def surfaceArea():
    import math
    r = eval(input("Enter the radius: "))
    a = 4 * math.pi * r ** 2
    print(a)

#surfaceArea()

# 2. Program to calculate cost per square inch of circular pizza
# I: diameter, price
# O: price * Area
# P: cost = price * pi* (diameter/2) ** 2

def pizzaCost():
    import math
    print("This program calculates the cost per square inch of a circular pizza, given its diameter and price.")
    # request and store diameter
    d = eval(input("Enter the diameter: "))
    p = eval(input("Enter the price for the pizza: "))
    cost = p * (math.pi * (d / 2) ** 2)
    print("The cost to produce this pizza is $", round(cost, 2))

pizzaCost()